name: 'Elemental action'
description: 'Use elemental to build derivatives'
inputs:
  version:
    description: 'Setup elemental'
    required: false
    default: 0.0.14
runs:
  using: 'composite'
  steps:
    - run: curl -LO https://github.com/rancher-sandbox/elemental/releases/download/v0.0.14/elemental-v0.0.14-Linux-x86_64.tar.gz
      shell: bash
    - run: ls
      shell: bash
    - run: tar -xvf elemental-v${{ inputs.version }}-Linux-x86_64.tar.gz
      shell: bash
    - run: chmod +x elemental
      shell: bash
    - run: sudo cp elemental /usr/bin/elemental
      shell: bash
